skip = 4
date_format = "%d.%m.%y"
number_locale = "de"
[map]
"Zahlungspflichtige\\*r" = "party1"
"Zahlungsempfänger\\*in" = "party2"
"Buchungsdatum" = "date"
"Betrag" = "amount"
"Buchungstext" = "Verwendungszweck"
